name: Test ipfs-crust-action
on:
  # mannual trigger
  workflow_dispatch:

jobs:
  pin_on_crust:
    name: test ipfs-crust-action
    runs-on: ubuntu-latest
    steps:
      - name: Pin to Crust
        id: pintocrust
        uses: crustio/ipfs-crust-action@v2.0.6
        continue-on-error: true
        with:
          cid: QmQRztEoR228Pzc7KrJEeTMxPf1W8UAnMA9RS1123W4kRH
          seeds: ${{ secrets.CRUST_SEEDS }}
