name: Test ipfs-crust-action
on:
  # mannual trigger
  workflow_dispatch:
    inputs:
      cid:
        description: 'CID to pin'
        required: true

jobs:
  pin_on_crust:
    name: test ipfs-crust-action
    runs-on: ubuntu-latest
    steps:
      - name: Pin to Crust
        id: pintocrust
        uses: crustio/ipfs-crust-action@main
        continue-on-error: true
        with:
          cid: ${{ github.event.inputs.cid }}
          seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Crust returns
        run: echo "Pin ${{ steps.pintocrust.outputs.res }}"